#! /bin/sh

# xset fp+ /usr/share/fonts/bitmap &
pgrep -x sxhkd > /dev/null || sxhkd &

# pgrep bspswallow || bspswallow &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0
# bspc monitor -d I II III IV V VI VII VIII IX X

# bspc config pointer_modifier         mod4
bspc config focus_follows_pointer    true
bspc config pointer_follows_focus    true
# bspc config pointer_motion_interval  5

# killall bspswallow
# pidof bspswallow | bspswallow &
# ~/.config/bspwm/scripts/bspfullscreen &

# border/gaps
bspc config border_width     1
# bspc config top_padding      0
# bspc config right_padding    5
# bspc config left_padding     5
# bspc config bottom_padding   -10
bspc config top_padding      -10
bspc config right_padding    -10
bspc config left_padding     -10
bspc config bottom_padding   -16

bspc config window_gap       10

bspc config focused_border_color "#938AA9"
bspc config normal_border_color "#000000"
bspc config presel_feedback_color "#000000"
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config single_monocle false
bspc config ignore_ewmh_focus false

bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true

###Rules
# Cleanup
# bspc rule -r '*'
# R feh       state=floating
# R freeze    state=floating
# R tabbed    state=floating
# R Gcolor3   state=floating
# R floating  state=floating

# State rules
bspc rule -a "dmenu" state=floating
bspc rule -a St:dropdown state=floating #sticky=on
# bspc rule -a "Sxiv" state=floating rectangle=1824x1026+40+19
# bspc rule -a "mpv" state=floating
bspc rule -a "Zathura" state=tiled

# Assignment rules
# bspc rule -a "qutebrowser" desktop=^1 follow=on
# bspc rule -a *:*:aerc desktop=^2 follow=on
# bspc rule -a *:*:ikhal desktop=^2 follow=on
# bspc rule -a *:*:Tasks desktop=^2 follow=on
#bspc rule -a libreoffice-* desktop=^3 follow=on #Fix me
# bspc rule -a "Zathura" desktop=^3 follow=on
# bspc rule -a *:*:weechat desktop=^6 follow=on
# bspc rule -a *:*:slack-term desktop=^6 follow=on
# bspc rule -a *:*:Spotify desktop=^7 follow=on

### Non-bspwm specific settings
# xset s 180 120
# xset dpms 305
xset r rate 120 150
#xset -b
# Handles cursor problem
# xsetroot -cursor_name left_ptr

# double border
# ~/.config/bspwm/scripts/dborders.sh &

# background
# feh --bg-scale ~/Pictures/Wallpapers/abstraaaaact.jpg
# hsetroot -solid "#263238" &
# hsetroot -solid "#1F2430" &
hsetroot -solid "#000000" &
# hsetroot -solid "#E82424" &

# poolybaaaaaar
~/.config/polybar/launch.sh &
#network
nm-applet &     #network
# compositor
# picom -b --experimental-backends &

# conky
# .config/scripts/launch_conky.sh

# setxkbmap -option caps:escape
# xss-lock --transfer-sleep-lock -- i3lock --nofork

bspc config wm_name LG3D

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

# Load Bitmap Fonts
# xset +fp ~/.local/share/fonts &
# xset fp rehash &
# xset fp+ /usr/share/fonts/bitmap &

# made single windows on desktop monocle
# /home/pierre/.config/bspwm/remove_border_only_one_windows.sh

# maps capslock to escape
# xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'
